version: "3.9"

services:
  server:
    build:
      context: ./
      dockerfile: ./server.dev.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./reader:/app/reader
      - ./server:/app/server
      - ${PWD}/.env:/app/server/.env
      - ${PWD}/.env:/app/reader/.env
      - /app/server/node_modules
      - /app/reader/node_modules
    env_file:
      - ./.env
    init: true
    tty: true

  client:
    build:
      context: ./
      dockerfile: ./client.dev.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./reader:/app/reader
      - ./server:/app/server
      - /app/server/node_modules
      - /app/reader/node_modules
    env_file:
      - ./.env
    init: true
    tty: true
    environment:
      - "KEYCLOAK_URL=http://keycloak:8080"
      - "SERVER_URL=http://server:3001"

  keycloak:
    env_file:
      - ./.env
    image: keycloak
    environment:
      - KC_HOSTNAME=0.0.0.0
      - HOSTNAME=0.0.0.0
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8080:8080"
      - "9990:9990"
    entrypoint:
      - /opt/keycloak/bin/kc.sh
      - "start-dev --hostname 0.0.0.0"

networks:
  default:
    internal: false
    driver: bridge