version: "3.9"

services:
  prod:
    image: 'languagetrainer-prod'
    ports:
      - "3001:3001"
      - "8080:8080"
      - "8000:8000"
    env_file:
      - ./.prod.env
    init: true
    tty: true
    

